### ISSUE TITLE
Swift stdlib leaks on constraint creation

### ISSUE THREAD

**Issue by frogcjn** [SnapKit/SnapKit#363]
### New Issue Checklist
- [x] I have looked at the [Documentation](http://snapkit.io/docs)
- [x] I have read the [F.A.Q.](http://snapkit.io/faq)
- [x] I have filled out this issue template.
### Issue Info

| Info | Value |
| --- | --- |
| Platform | iOS |
| Platform Version | 10.1 |
| SnapKit Version | 3.0.2 |
| Integration Method | cocoapods |
### Issue Description

Too many leaks on Swift.Array<SnapKit.LayoutConstraint>, and it is always increasing
<img width="509" alt="2016-10-27 13 42 16" src="https://cloud.githubusercontent.com/assets/1777562/19755870/422e23a6-9c4b-11e6-93ff-6045e24747ea.png">

**Comment by GeekYW** [comment]
我在Xcode 8.0 上面用的是3.0.2 怎么还是提示更新，一更新之后就报错

**Comment by frogcjn** [comment]
@GeekYW, This is SnapKit and most of developers using SnapKit cannot speak Chinese. And your problem is not related to my issue. Please open your own issue. Thanks.

**Comment by GeekYW** [comment]
OK

**Comment by chlumik** [comment]
I have the same problem.

**Comment by frogcjn** [comment]
It might be the Apple side problem, but needs an investigation. I have report several bugs, but still need find this one.

**Comment by robertjpayne** [comment]
@frogcjn have you run instruments with the leaks profiler on? That's a much more accurate way to gather this information and share it if you can please.

**Comment by frogcjn** [comment]
I think it is probably from this property.
```Swift
public class Constraint {
    private var layoutConstraints: [LayoutConstraint]
}
```
But in my Instruments, it is hard to investigate, how to make the trace shows the function name from other framework?
<img width="1282" alt="2016-10-27 17 31 51" src="https://cloud.githubusercontent.com/assets/1777562/19762225/bf78c5e4-9c6b-11e6-8856-94d96244912b.png">

**Comment by robertjpayne** [comment]
@frogcjn sometimes instruments really sucks at picking up symbols, one thing you can do is make sure your "Profile" scheme step is set to use "Debug" instead of Release mode, sometimes it helps.

**Comment by hooliooo** [comment]
Is there an update on this issue? I'm experiencing the same thing

**Comment by rmnblm** [comment]
I'm facing the same issue. I subclassed a `UITableViewCell` and added some views to it. 
The memory usage is increasing incredibly fast at this part of code (when I comment it out, there are no problems):

``` swift
contentView.snp.makeConstraints { make -> Void in
    make.leftMargin.rightMargin.equalTo(8)
}
```

**Comment by lianweiqin** [comment]
![default](https://cloud.githubusercontent.com/assets/8318337/20132502/4424aef2-a69e-11e6-9379-4741a9c71209.png)

Facing the same problem...  : (

**Comment by CaptainKurt** [comment]
Is anyone facing this problem with OS X?

**Comment by joaoritter** [comment]
I'm also having the memory leak issue on iOS 10.1 using Snapkit 3.0.2. Looking forward to a fix, this library is great!

**Comment by hooliooo** [comment]
@robertjpayne is there any update to this issue? Do you need anymore information?

**Comment by robertjpayne** [comment]
@hooliooo I'll try and squeeze this in tonight, don't need more information just more time running a retail business on the side with Christmas holiday rush already kicking in!

**Comment by robertjpayne** [comment]
For everyone watching this I did a bit more digging today. This bug isn't with SnapKit it's solely related to Swift and I'm not 100% sure how to fix this yet.

Internally I store `NSLayoutConstraint` objects in a Swift `[NSLayoutConstraint]` array. If this array is switched to be a NSMutableArray instead of a Swift array the leaks go away.

Unfortunately it impacts performance quit a lot since bridging isn't free and I'm still trying to find a solution.

**Comment by robertjpayne** [comment]
Ok final update:

The leak isn't coming from SnapKit, rather it's the Swift stdlib, I've thoroughly looked into this using manual deinit tracking and every object created gets released when the views/view controllers.

More worrying this leak doesn't always happen, it seems to happen at random, I've been running instruments for an hour pushing and popping a view controller creating constraints and sorts and instruments sometimes shows leaks every 10s sometimes it does not.

I'm still trying to find a work around but thus far have not had any luck and can't figure out why this particular array leaks.

**Comment by hooliooo** [comment]
@robertjpayne thanks for the update! Keep us posted

**Comment by robertjpayne** [comment]
So a bit more on this, I thought I had fixed it but really I just introduced a bad bug, it relates to how SnapKit is using associated objects specifically this code:

```
internal var constraints: [Constraint] {
    return self.constraintsSet.allObjects as! [Constraint]
}

internal func add(constraints: [Constraint]) {
    let constraintsSet = self.constraintsSet
    for constraint in constraints {
        constraintsSet.add(constraint)
    }
}

internal func remove(constraints: [Constraint]) {
    let constraintsSet = self.constraintsSet
    for constraint in constraints {
        constraintsSet.remove(constraint)
    }
}

private var constraintsSet: NSMutableSet {
    let constraintsSet: NSMutableSet
    
    if let existing = objc_getAssociatedObject(self, &constraintsKey) as? NSMutableSet {
        constraintsSet = existing
    } else {
        constraintsSet = NSMutableSet()
        objc_setAssociatedObject(self, &constraintsKey, constraintsSet, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)
    }
    return constraintsSet
    
}
```

in LayoutConstraintItem.swift

For some reason these retains are causing the leak messages, I don't really get how or why though since the stored `Constraint` object's are properly getting released…

**Comment by robertjpayne** [comment]
A little more digging, it's actually just the Swift internal array buffer that is leaking, all of SnapKit's objects are properly getting cleaned up... It looks like for every single `Constraint` it's underlying array for `[LayoutConstraint]` is somehow not fixing itself…

**Comment by robertjpayne** [comment]
At this rate I may use the unmanaged API's and manually retain/release these `LayoutConstraint` objects...

**Comment by robertjpayne** [comment]
Anyone else have good instrument traces they can trace? Is there reliably huge memory growth for anyone?

I'm at a loss of how to fix this ( if it is even fixable ) it seems like Swift is allocating extra memory for the contiguous array buffers but then never freeing it. All of SnapKit's objects are getting freed just fine.

**Comment by robertjpayne** [comment]
@frogcjn @hooliooo @joaoritter any of you three see runaway growth of "persistent object" counts in the `Allocations` portion of leaks instrument?

Particularly looking for growth of anything with the word `Constraint`. Because at this point I'm nearly positive that Instruments is claiming these things are leaking but they are not. Allocations never shows me any runaway growth of any SnapKit objects or even Malloc's either.

<img width="1396" alt="screen shot 2016-11-24 at 5 17 39 pm" src="https://cloud.githubusercontent.com/assets/214288/20586574/0935284e-b26a-11e6-946c-9e5c7aa9a2d8.png">

**Comment by qyning** [comment]
The problem seems to only appear in iOS10

**Comment by marcotolman** [comment]
Maybe fixed in 10.2?

**Comment by soapsign** [comment]
Just tested, the problem still exists. I think people should be warmed before using SnapKit in code base extensively until this leak have been fixed.

**Comment by robertjpayne** [comment]
@soapsign please read the full thread -- as far as I can tell this isn't actually a memory leak it's just instruments incorrectly reporting it is. After doing exhaustive testing for long periods of time actual memory grown via Activity Monitor on the device shows no expansion of memory.

**Comment by soapsign** [comment]
@robertjpayne OK. I have confirmed this isn't a memory leak too after checking thoughtfully.

**Comment by robertjpayne** [comment]
Interesting looking at the above ReactiveCocoa link it looks like this may be because of how Swift deallocates weak refs.

I'm closing this issue because it's *not* a bug but rather just an instruments issue.
